export const vendorData = {
  Venues: [
    {
      id: 1,
      name: "Elegant Hall",
      rating: 4.7,
      description: "A luxurious venue for your big day.",
      cost: 1200,
    },
    {
      id: 2,
      name: "Garden Paradise",
      rating: 4.5,
      description: "A serene garden setting for your wedding.",
      cost: 1500,
    },
    {
      id: 3,
      name: "City Ballroom",
      rating: 4.8,
      description: "A modern venue with all the amenities.",
      cost: 1300,
    },
  ],
  Photography: [
    {
      id: 4,
      name: "Picture Perfect",
      rating: 4.9,
      description: "Capture every moment beautifully.",
      cost: 800,
    },
    {
      id: 5,
      name: "Memory Makers",
      rating: 4.6,
      description: "Expert photographers for your special day.",
      cost: 1000,
    },
    {
      id: 6,
      name: "Snapshot Studios",
      rating: 4.7,
      description: "Professional photography services.",
      cost: 900,
    },
  ],
  Catering: [
    {
      id: 7,
      name: "Gourmet Delights",
      rating: 4.8,
      description: "Exquisite cuisine to delight your guests.",
      cost: 2000,
    },
    {
      id: 8,
      name: "Feast & Fête",
      rating: 4.6,
      description: "Exceptional catering for all occasions.",
      cost: 1800,
    },
    {
      id: 9,
      name: "Culinary Creations",
      rating: 4.9,
      description: "Innovative menus for your event.",
      cost: 2100,
    },
  ],
  Decor: [
    {
      id: 10,
      name: "Elegant Events",
      rating: 4.8,
      description: "Transform your venue with beautiful decor.",
      cost: 1700,
    },
    {
      id: 11,
      name: "Stunning Stages",
      rating: 4.7,
      description: "Creative decor solutions for your event.",
      cost: 1600,
    },
    {
      id: 12,
      name: "Floral Fantasy",
      rating: 4.9,
      description: "Breathtaking floral arrangements and decor.",
      cost: 1900,
    },
  ],
  Music: [
    {
      id: 13,
      name: "Melody Makers",
      rating: 4.7,
      description: "Talented musicians for your wedding.",
      cost: 1400,
    },
    {
      id: 14,
      name: "DJ Beats",
      rating: 4.8,
      description: "Professional DJ services for your event.",
      cost: 1500,
    },
    {
      id: 15,
      name: "Harmony Bands",
      rating: 4.9,
      description: "Live music to set the perfect tone.",
      cost: 1600,
    },
  ],
  Attire: [
    {
      id: 16,
      name: "Bridal Bliss",
      rating: 4.9,
      description: "Find the perfect dress for your big day.",
      cost: 3000,
    },
    {
      id: 17,
      name: "Groom's Elegance",
      rating: 4.8,
      description: "Stylish suits and tuxedos for the groom.",
      cost: 2500,
    },
    {
      id: 18,
      name: "Wedding Wardrobe",
      rating: 4.7,
      description: "Exclusive bridal and groom attire.",
      cost: 2800,
    },
  ],
};
